export const COUNTRY_CITIES = {
  "BEN": [
    "Abomey",
    "Abomey-Calavi",
    "Allada",
    "Banikoara",
    "Bassila",
    "Bembèrèkè",
    "Bohicon",
    "Bétérou",
    "Commune of Agbangnizoun",
    "Commune of Athieme",
    "Commune of Djougou",
    "Comé",
    "Cotonou",
    "Cové",
    "Dassa-Zoumé",
    "Djakotomey",
    "Djougou",
    "Dogbo",
    "Guilmaro",
    "Hinvi",
    "Hévié",
    "Kandi",
    "Kétou",
    "Lokossa",
    "Malanville",
    "Natitingou",
    "Nikki",
    "Ouidah",
    "Parakou",
    "Pobé",
    "Porto-Novo",
    "Sakété",
    "Savalou",
    "Savé",
    "Tanguieta",
    "Tchaourou"
  ],
  "BFA": [
    "Banfora",
    "Barani",
    "Batié",
    "Bazega Province",
    "Bobo-Dioulasso",
    "Bogandé",
    "Boromo",
    "Boulsa",
    "Boussé",
    "Dano",
    "Diapaga",
    "Diébougou",
    "Djibo",
    "Dori",
    "Dédougou",
    "Fada N'gourma",
    "Garango",
    "Gayéri",
    "Gnagna Province",
    "Gorom-Gorom",
    "Goulouré",
    "Gourcy",
    "Houndé",
    "Kadiogo Province",
    "Kaya",
    "Kokologo",
    "Kombissiri",
    "Kongoussi",
    "Koudougou",
    "Koupéla",
    "Kouritenga Province",
    "Léo",
    "Manga",
    "Nahouri Province",
    "Nouna",
    "Ouagadougou",
    "Ouahigouya",
    "Ouargaye",
    "Oubritenga",
    "Pama",
    "Pitmoaga",
    "Province de la Bougouriba",
    "Province de la Comoé",
    "Province de la Komandjoari",
    "Province de la Kompienga",
    "Province de la Kossi",
    "Province de la Léraba",
    "Province de la Sissili",
    "Province de la Tapoa",
    "Province de l’Oudalan",
    "Province des Balé",
    "Province des Banwa",
    "Province du Bam",
    "Province du Boulgou",
    "Province du Boulkiemdé",
    "Province du Ganzourgou",
    "Province du Gourma",
    "Province du Houet",
    "Province du Ioba",
    "Province du Koulpélogo",
    "Province du Kourwéogo",
    "Province du Kénédougou",
    "Province du Loroum",
    "Province du Mouhoun",
    "Province du Namentenga",
    "Province du Nayala",
    "Province du Noumbièl",
    "Province du Passoré",
    "Province du Poni",
    "Province du Sanguié",
    "Province du Sanmatenga",
    "Province du Soum",
    "Province du Sourou",
    "Province du Séno",
    "Province du Tuy",
    "Province du Yagha",
    "Province du Yatenga",
    "Province du Ziro",
    "Province du Zondoma",
    "Pô",
    "Réo",
    "Salanso",
    "Sapouy",
    "Sindou",
    "Tenkodogo",
    "Titao",
    "Toma",
    "Tougan",
    "Yako",
    "Ziniaré",
    "Zorgo",
    "Zoundweogo Province"
  ],
  "CMR": [
    "Abong Mbang",
    "Akom II",
    "Akono",
    "Akonolinga",
    "Ambam",
    "Babanki",
    "Bafang",
    "Bafia",
    "Bafoussam",
    "Bali",
    "Bamenda",
    "Bamendjou",
    "Bamusso",
    "Bana",
    "Bandjoun",
    "Bangangté",
    "Bankim",
    "Bansoa",
    "Banyo",
    "Batibo",
    "Batouri",
    "Bazou",
    "Bekondo",
    "Belo",
    "Bertoua",
    "Bogo",
    "Bonabéri",
    "Boyo",
    "Buea",
    "Bélabo",
    "Bélel",
    "Bétaré Oya",
    "Diang",
    "Dibombari",
    "Dimako",
    "Dizangué",
    "Djohong",
    "Douala",
    "Doumé",
    "Dschang",
    "Edéa",
    "Essé",
    "Eséka",
    "Fako Division",
    "Faro Department",
    "Fontem",
    "Foumban",
    "Foumbot",
    "Fundong",
    "Garoua",
    "Garoua Boulaï",
    "Guider",
    "Hauts-Plateaux",
    "Jakiri",
    "Kaélé",
    "Kontcha",
    "Koung-Khi",
    "Kousséri",
    "Koza",
    "Kribi",
    "Kumba",
    "Kumbo",
    "Lagdo",
    "Lebialem",
    "Limbe",
    "Lolodorf",
    "Loum",
    "Makary",
    "Mamfe",
    "Manjo",
    "Maroua",
    "Mayo-Banyo",
    "Mayo-Louti",
    "Mayo-Rey",
    "Mayo-Sava",
    "Mayo-Tsanaga",
    "Mbalmayo",
    "Mbam-Et-Inoubou",
    "Mbandjok",
    "Mbang",
    "Mbanga",
    "Mbankomo",
    "Mbengwi",
    "Mbouda",
    "Mefou-et-Akono",
    "Melong",
    "Meïganga",
    "Mfoundi",
    "Mindif",
    "Minta",
    "Mme-Bafumen",
    "Mokolo",
    "Mora",
    "Mouanko",
    "Mundemba",
    "Mutengene",
    "Muyuka",
    "Mvangué",
    "Mvila",
    "Nanga Eboko",
    "Ndelele",
    "Ndikiniméki",
    "Ndom",
    "Ngambé",
    "Ngaoundéré",
    "Ngomedzap",
    "Ngoro",
    "Ngou",
    "Nguti",
    "Njinikom",
    "Nkongsamba",
    "Nkoteng",
    "Noun",
    "Ntui",
    "Obala",
    "Okoa",
    "Okola",
    "Ombésa",
    "Penja",
    "Pitoa",
    "Poli",
    "Rey Bouba",
    "Saa",
    "Sangmélima",
    "Somié",
    "Tcholliré",
    "Tibati",
    "Tignère",
    "Tiko",
    "Tonga",
    "Vina",
    "Wum",
    "Yabassi",
    "Yagoua",
    "Yaoundé",
    "Yokadouma",
    "Yoko",
    "Ébolowa",
    "Évodoula"
  ],
  "CAF": [
    "Alindao",
    "Bambari",
    "Bamingui",
    "Bangassou",
    "Bangui",
    "Baoro",
    "Batangafo",
    "Berberati",
    "Bimbo",
    "Birao",
    "Boali",
    "Bocaranga",
    "Boda",
    "Boganangone",
    "Bossangoa",
    "Bouar",
    "Bouca",
    "Bozoum",
    "Bria",
    "Carnot",
    "Damara",
    "Gambo",
    "Gamboula",
    "Grimari",
    "Ippy",
    "Kabo",
    "Kaga Bandoro",
    "Kaga-Bandoro",
    "Kembé",
    "Kouango",
    "Mbaiki",
    "Mobaye",
    "Mongoumba",
    "Ndélé",
    "Nola",
    "Obo",
    "Ouadda",
    "Ouanda-Djallé",
    "Ouango",
    "Paoua",
    "Rafai",
    "Sibut",
    "Zemio"
  ],
  "COM": [
    "Adda-Douéni",
    "Antsahé",
    "Assimpao",
    "Bahani",
    "Bambadjani",
    "Bambao",
    "Bandajou",
    "Barakani",
    "Bimbini",
    "Boungouéni",
    "Bouni",
    "Chandra",
    "Chezani",
    "Chindini",
    "Chironkamba",
    "Chitrouni",
    "Chouani",
    "Daji",
    "Dembéni",
    "Djoyézi",
    "Domoni",
    "Douniani",
    "Dzahadjou",
    "Dziani",
    "Fomboni",
    "Foumbouni",
    "Hajoho",
    "Hantsindzi",
    "Harembo",
    "Hoani",
    "Héroumbili",
    "Itsandra",
    "Itsandzéni",
    "Ivouani",
    "Kangani",
    "Kavani",
    "Koki",
    "Koni-Djodjo",
    "Koni-Ngani",
    "Koua",
    "Kyo",
    "Limbi",
    "Lingoni",
    "Madjeouéni",
    "Magnassini-Nindri",
    "Mandza",
    "Maraharé",
    "Mavingouni",
    "Mbéni",
    "Mirontsi",
    "Mitsamiouli",
    "Mitsoudjé",
    "Mjamaoué",
    "Mjimandra",
    "Mnoungou",
    "Mohoro",
    "Moroni",
    "Moutsamoudou",
    "Moya",
    "Mramani",
    "Mrémani",
    "Mtakoudja",
    "Mtsamdou",
    "Mvouni",
    "Nioumachoua",
    "Nioumamilima",
    "Ntsaouéni",
    "Ntsoudjini",
    "Ongoni",
    "Ouanani",
    "Ouani",
    "Ouellah",
    "Ouhozi",
    "Ourovéni",
    "Oussivo",
    "Ouzini",
    "Pajé",
    "Patsi",
    "Salimani",
    "Sima",
    "Singani",
    "Séléa",
    "Tsidjé",
    "Tsimbeo",
    "Vanadjou",
    "Vanambouani",
    "Vouani",
    "Ziroudani"
  ],
  "COG": [
    "Brazzaville",
    "Djambala",
    "Dolisie",
    "Ewo",
    "Gamboma",
    "Impfondo",
    "Kayes",
    "Kinkala",
    "Loandjili",
    "Madingou",
    "Makoua",
    "Mossendjo",
    "Ouésso",
    "Owando",
    "Pointe-Noire",
    "Sibiti",
    "Sémbé"
  ],
  "COD": [
    "Aketi",
    "Bandundu",
    "Basoko",
    "Beni",
    "Boende",
    "Bolobo",
    "Boma",
    "Bondo",
    "Bongandanga",
    "Bosobolo",
    "Bukama",
    "Bukavu",
    "Bulungu",
    "Bumba",
    "Bunia",
    "Businga",
    "Buta",
    "Butembo",
    "Gandajika",
    "Gbadolite",
    "Gemena",
    "Goma",
    "Haut Katanga",
    "Ilebo",
    "Inongo",
    "Isiro",
    "Kabalo",
    "Kabare",
    "Kabinda",
    "Kalemie",
    "Kambove",
    "Kamina",
    "Kampene",
    "Kasangulu",
    "Kasongo",
    "Kasongo-Lunda",
    "Kikwit",
    "Kindu",
    "Kinshasa",
    "Kipushi",
    "Kisangani",
    "Kongolo",
    "Libenge",
    "Likasi",
    "Lisala",
    "Lodja",
    "Lubao",
    "Lubumbashi",
    "Luebo",
    "Lukolela",
    "Lusambo",
    "Mangai",
    "Masina",
    "Matadi",
    "Mbandaka",
    "Mbanza-Ngungu",
    "Mbuji-Mayi",
    "Moanda",
    "Mushie",
    "Mweka",
    "Mwene-Ditu",
    "Nioki",
    "Sake",
    "Tshela",
    "Tshikapa",
    "Uvira",
    "Wamba",
    "Watsa",
    "Yangambi"
  ],
  "CIV": [
    "Abengourou",
    "Abidjan",
    "Abobo",
    "Aboisso",
    "Adiaké",
    "Adzopé",
    "Affery",
    "Agboville",
    "Agnibilékrou",
    "Agnéby-Tiassa",
    "Akoupé",
    "Anyama",
    "Arrah",
    "Ayamé",
    "Bafing",
    "Bangolo",
    "Biankouma",
    "Bingerville",
    "Bocanda",
    "Bondoukou",
    "Bongouanou",
    "Bonoua",
    "Botro",
    "Bouaflé",
    "Bouaké",
    "Bouna",
    "Bounkani",
    "Bélier",
    "Béoumi",
    "Béré",
    "Cavally",
    "Dabakala",
    "Dabou",
    "Daloa",
    "Danané",
    "Daoukro",
    "Dimbokro",
    "Divo",
    "Duekoué",
    "Folon",
    "Gagnoa",
    "Gbêkê",
    "Gbôklé",
    "Gontougo",
    "Grand-Bassam",
    "Grand-Lahou",
    "Grands-Ponts",
    "Guibéroua",
    "Guiglo",
    "Guémon",
    "Gôh",
    "Hambol",
    "Haut-Sassandra",
    "Iffou",
    "Indénié-Djuablin",
    "Issia",
    "Kabadougou",
    "Katiola",
    "Lakota",
    "Lôh-Djiboua",
    "Man",
    "Mankono",
    "Marahoué",
    "Moronou",
    "N'Zi",
    "Nawa",
    "Odienné",
    "Oumé",
    "Sakassou",
    "San-Pédro",
    "Sassandra",
    "Sinfra",
    "Sud-Comoé",
    "Séguéla",
    "Tabou",
    "Tanda",
    "Tiassalé",
    "Tonkpi",
    "Touba",
    "Toulépleu Gueré",
    "Toumodi",
    "Vavoua",
    "Worodougou",
    "Yamoussoukro",
    "Zuénoula"
  ],
  "GAB": [
    "Bitam",
    "Booué",
    "Cocobeach",
    "Fougamou",
    "Franceville",
    "Gamba",
    "Koulamoutou",
    "Lambaréné",
    "Lastoursville",
    "Libreville",
    "Lékoni",
    "Makokou",
    "Mayumba",
    "Mbigou",
    "Mimongo",
    "Mitzic",
    "Moanda",
    "Mouila",
    "Mounana",
    "Ndendé",
    "Ndjolé",
    "Ntoum",
    "Okondja",
    "Omboué",
    "Oyem",
    "Port-Gentil",
    "Tchibanga",
    "Zadie"
  ],
  "GIN": [
    "Beyla",
    "Beyla Prefecture",
    "Boffa",
    "Boke Prefecture",
    "Boké",
    "Camayenne",
    "Conakry",
    "Coyah",
    "Dalaba",
    "Dubréka",
    "Forécariah",
    "Fria",
    "Gaoual",
    "Gaoual Prefecture",
    "Gueckedou",
    "Kankan",
    "Kankan Prefecture",
    "Kerouane Prefecture",
    "Kimbo",
    "Kindia",
    "Koubia",
    "Koundara",
    "Koundara Prefecture",
    "Kouroussa",
    "Kérouané",
    "Labe Prefecture",
    "Labé",
    "Lelouma Prefecture",
    "Lola",
    "Lélouma",
    "Macenta",
    "Mali",
    "Mali Prefecture",
    "Mamou",
    "Mamou Prefecture",
    "Mandiana",
    "Mandiana Prefecture",
    "Nzerekore Prefecture",
    "Nzérékoré",
    "Pita",
    "Préfecture de Dubréka",
    "Préfecture de Forécariah",
    "Préfecture de Guékédou",
    "Sanguéya",
    "Siguiri",
    "Siguiri Prefecture",
    "Telimele Prefecture",
    "Tokonou",
    "Tondon",
    "Tougue Prefecture",
    "Tougué",
    "Télimélé",
    "Yomou",
    "Youkounkoun"
  ],
  "GNB": [
    "Bafatá",
    "Bissorã",
    "Bolama",
    "Buba",
    "Bubaque",
    "Cacheu",
    "Canchungo",
    "Catió",
    "Contuboel Sector",
    "Farim",
    "Gabú",
    "Mansôa",
    "Quebo",
    "Quinhámel"
  ],
  "GNQ": [
    "Aconibe",
    "Acurenam",
    "Ayene",
    "Añisoc",
    "Bata",
    "Bicurga",
    "Bitica",
    "Cogo",
    "Ebebiyin",
    "Evinayong",
    "Luba",
    "Machinda",
    "Malabo",
    "Mbini",
    "Mengomeyén",
    "Mikomeseng",
    "Mongomo",
    "Ncue",
    "Nsang",
    "Nsok",
    "Rebola",
    "Río Campo",
    "San Antonio de Palé",
    "Santiago de Baney"
  ],
  "MLI": [
    "Abeïbara",
    "Ansongo",
    "Araouane",
    "Bafoulabé",
    "Bamako",
    "Banamba",
    "Bandiagara",
    "Baroueli",
    "Bougouni",
    "Cercle de Bourem",
    "Cercle de Goundam",
    "Cercle de San",
    "Cercle d’Abeïbara",
    "Dire",
    "Djénné",
    "Douentza",
    "Douentza Cercle",
    "Gao",
    "Gao Cercle",
    "Goundam",
    "Gourma-Rharous Cercle",
    "Inékar",
    "Kangaba",
    "Kati",
    "Kayes",
    "Kidal",
    "Kinmparana",
    "Kita",
    "Kokofata",
    "Kolokani",
    "Kolondiéba",
    "Koulikoro",
    "Koutiala",
    "Koutiala Cercle",
    "Ké-Macina",
    "Markala",
    "Mopti",
    "Niafunké",
    "Ntossoni",
    "Sagalo",
    "San",
    "Sikasso",
    "Sokolo",
    "Ségou",
    "Timbuktu",
    "Ténenkou",
    "Yorosso"
  ],
  "NER": [
    "Abalak",
    "Agadez",
    "Aguié",
    "Alaghsas",
    "Arlit",
    "Ayorou",
    "Balleyara",
    "Bilma",
    "Birni N Konni",
    "Boboye Department",
    "Bouza",
    "Dakoro",
    "Diffa",
    "Dogondoutchi",
    "Dosso",
    "Département d' Illéla",
    "Département de Bilma",
    "Département de Birni Nkonni",
    "Département de Bouza",
    "Département de Dakoro",
    "Département de Diffa",
    "Département de Dogondoutchi",
    "Département de Dosso",
    "Département de Filingué",
    "Département de Gaya",
    "Département de Gouré",
    "Département de Kantché",
    "Département de Keïta",
    "Département de Loga",
    "Département de Madaoua",
    "Département de Mayahi",
    "Département de Maïné-Soroa",
    "Département de Nguigmi",
    "Département de Ouallam",
    "Département de Say",
    "Département de Tahoua",
    "Département de Tchin-Tabaraden",
    "Département de Tchirozérine",
    "Département de Tessaoua",
    "Département de Tânout",
    "Département d’Aguié",
    "Filingué",
    "Gaya",
    "Gouré",
    "Guidan Roumdji Department",
    "Illéla",
    "Keïta",
    "Kollo",
    "Kollo Department",
    "Madaoua",
    "Madarounfa",
    "Magaria",
    "Maradi",
    "Matamey",
    "Mayahi",
    "Maïné Soroa",
    "Mirriah",
    "Nguigmi",
    "Ouallam",
    "Say",
    "Tahoua",
    "Tanout",
    "Tchintabaraden",
    "Tera Department",
    "Tessaoua",
    "Tibiri",
    "Tillaberi Department",
    "Tillabéri",
    "Téra",
    "Zinder"
  ],
  "SEN": [
    "Adéane",
    "Bignona",
    "Dakar",
    "Dakar Department",
    "Dara",
    "Diawara",
    "Diofior",
    "Département de Salémata",
    "Fatick Department",
    "Foundiougne",
    "Gandiaye",
    "Goléré",
    "Goudomp Department",
    "Guinguinéo",
    "Guédiawaye Department",
    "Guéoul",
    "Joal-Fadiout",
    "Kaffrine",
    "Kanel",
    "Kaolack",
    "Kayar",
    "Khombole",
    "Kolda",
    "Kolda Department",
    "Koungheul",
    "Kédougou",
    "Kédougou Department",
    "Linguere Department",
    "Louga",
    "Marsassoum",
    "Matam",
    "Matam Department",
    "Mbacké",
    "Mbaké",
    "Mbour",
    "Mermoz Boabab",
    "Mékhé",
    "Ndibène Dahra",
    "Ndioum",
    "Ndofane",
    "Nguékhokh",
    "Nioro du Rip",
    "N’diareme limamoulaye",
    "Ouro Sogui",
    "Oussouye",
    "Passi",
    "Pikine",
    "Pikine Department",
    "Polel Diaoubé",
    "Pourham",
    "Pout",
    "Ranérou",
    "Richard-Toll",
    "Rosso",
    "Rufisque Department",
    "Saint-Louis",
    "Saraya",
    "Sokone",
    "Sédhiou",
    "Sémé",
    "Tambacounda",
    "Tambacounda Department",
    "Thiès",
    "Thiès Nones",
    "Tiadiaye",
    "Tionk Essil",
    "Tivaouane",
    "Tiébo",
    "Touba",
    "Vélingara",
    "Waoundé",
    "Warang",
    "Ziguinchor"
  ],
  "TCD": [
    "Abéché",
    "Adré",
    "Am Timan",
    "Aozou",
    "Ati",
    "Benoy",
    "Beïnamar",
    "Biltine",
    "Bitkine",
    "Bokoro",
    "Bol",
    "Bongor",
    "Béboto",
    "Bébédja",
    "Béré",
    "Doba",
    "Fada",
    "Faya-Largeau",
    "Goundi",
    "Gounou Gaya",
    "Goz Beïda",
    "Goz Béïda",
    "Guelendeng",
    "Iriba",
    "Kelo",
    "Koumra",
    "Kyabé",
    "Lac Wey",
    "Laï",
    "Mao",
    "Massaguet",
    "Massakory",
    "Mboursou Léré",
    "Melfi",
    "Mongo",
    "Moundou",
    "Moussoro",
    "Moïssala",
    "Oum Hadjer",
    "Pala",
    "Sarh"
  ],
  "TGO": [
    "Amlamé",
    "Aného",
    "Atakpamé",
    "Badou",
    "Bafilo",
    "Bassar",
    "Dapaong",
    "Kandé",
    "Kara",
    "Kpalimé",
    "Lomé",
    "Niamtougou",
    "Notsé",
    "Pagouda",
    "Préfecture de Bassar",
    "Sansanné-Mango",
    "Sokodé",
    "Sotouboua",
    "Tabligbo",
    "Tchamba",
    "Tsévié",
    "Vogan"
  ]
};
