export const SUBJECTS = [
  'Toutes',
  'Mathématiques',
  'Physique-Chimie',
  'SVT',
  'Français',
  'Anglais',
  'Histoire-Géographie',
  'Philosophie',
  'Espagnol',
  'Allemand',
  'Informatique / TIC',
  'Éducation Physique et Sportive (EPS)',
  'Éducation Civique et Morale (ECM)',
  'Arts Plastiques',
  'Musique',
  'Économie',
  'Lecture',
  'Écriture',
  'Éveil Scientifique',
  'Entrepreneuriat',
  'Latin',
  'Mécanique'
]
